### ISSUE TITLE
Expand to 🇫🇮 Finland

### ISSUE THREAD

**Issue by Joonalai** [osmontrouge/caresteouvert#375]
This idea is great! We at [Gispo](https://www.gispo.fi/en/home/) would like to help getting the coverage to Finland as well. We will start translating process soon.

Please read https://github.com/osmontrouge/caresteouvert/wiki/Expand-%22%C3%87a-reste-ouvert%22-to-another-country first.

Please check the following requirements:

- [x] You are a team of at least 2 people experienced with OpenStreetMap
- [x] Translate the app via transifex with your country languages
- [x] Translate some content of the blog to help newcomers (how to create a new shop, the about page, ...)
- [x] Start gathering data about shop open or closed nation wide in https://github.com/PanierAvide/Covid_enseignes/
- [ ] Once everything has been done and the data have been loaded, you should be busy getting media coverage. So the map will have a lot of contribution and be quickly useful.

Others questions:

- if you want a localized domain name, please tell us which one: 
- Each lockdown is different, what shops are open or closed in your country? What should be done in the category list?

**Comment by Joonalai** [comment]
Transifex translation to Finnish is complete.

**Comment by francois2metz** [comment]
@govvin Where you could we find the localized blogs posts? Could you create them in the repository under the ~/articles/fi?

**Comment by Joonalai** [comment]
@francois2metz we have started building our own blog site already where the articles will be updated. We will also use our own domain *ollaanauki.fi*. Do we get an ip address or how do we use our domain to host the service?

**Comment by francois2metz** [comment]
@Joonalai for the map, you can use a CNAME that point to `www.caresteouvert.fr`. 
If you want to use the bare domain `ollaanauki.fi`, you can use an ALIAS (if possible) or use the IP `5.104.101.30`.

**Comment by Joonalai** [comment]
@francois2metz thank you. We used subdomain `kartta.ollaanauki.fi` with CNAME pointing to `www.caresteouvert.fr`. It should be working within 2 hours.

The other information for `config.json`:
* locale: fi
* domain: kartta.ollaanauki.fi
* brand: ollaanauki
* brand_text: Ollaan auki
* government: https://valtioneuvosto.fi/tietoa-koronaviruksesta/
* blog: https://blog.ollaanauki.fi/
* shopMissing: https://blog.ollaanauki.fi/lisaa_palvelu/
* townhalls: https://blog.ollaanauki.fi/kaupungeille-ja-yhteisoille/
* about: https://blog.ollaanauki.fi/meista/
* press: https://blog.ollaanauki.fi/lehdistolle/
* disclaimer: https://blog.ollaanauki.fi/vastuuvapauslauseke/

**Comment by Joonalai** [comment]
@francois2metz http://kartta.ollaanauki.fi/ is now up but it says "The application does not exist".

**Comment by francois2metz** [comment]
I configured the domain and added the config. The brand is not done as one asset is still missing.

**Comment by Joonalai** [comment]
@francois2metz wonderful, thank you! Do you need our help with the missing asset?

**Comment by posikifi** [comment]
@francois2metz There is 18 brands added. We are working with OSMers during the weekend add more to OSM.

**Comment by francois2metz** [comment]
We plan to update the data today so you will have a better view of what is missing or not.

**Comment by PanierAvide** [comment]
Finland enabled by 9c7cc8c2bacb18df7218ad05518b59156821d448, data will be visible in ~1h :smiley:

**Comment by PanierAvide** [comment]
Closing the issue as Finland is now live.
